In [1]:
import numpy as np

In [2]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [3]:
type(np.array([2,3,4,5,6]))

numpy.ndarray

In [4]:
np.array([[2,3,4],[5,6,7]])

array([[2, 3, 4],
       [5, 6, 7]])

In [6]:
l=[[1,2,3,4],[5,6,7,8]]
l[0][0]

1

In [11]:
a=np.array([1,2,3,4],ndmin=3)

In [12]:
a

array([[[1, 2, 3, 4]]])

In [21]:
arr=np.array([[1,2,3],[4,5,6],[6,7,8]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [22]:
arr.ndim

2

In [53]:
np.random.randint(1,10,(4,4))

array([[8, 8, 8, 9],
       [6, 9, 5, 3],
       [7, 9, 2, 8],
       [1, 9, 6, 8]])

In [55]:
np.random.randint(1,10,(4,4,2))

array([[[1, 3],
        [3, 3],
        [3, 7],
        [6, 9]],

       [[4, 4],
        [4, 6],
        [6, 3],
        [1, 6]],

       [[5, 6],
        [9, 1],
        [2, 7],
        [5, 9]],

       [[6, 6],
        [8, 6],
        [6, 6],
        [3, 9]]])