In [1]:
import numpy as np

In [2]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [3]:
type(np.array([2,3,4,5,6]))

numpy.ndarray

In [4]:
np.array([[2,3,4],[5,6,7]])

array([[2, 3, 4],
       [5, 6, 7]])

In [5]:
l=[[1,2,3,4],[5,6,7,8]]
l[0][0]

1

In [6]:
a=np.array([1,2,3,4],ndmin=3)

In [7]:
a

array([[[1, 2, 3, 4]]])

In [8]:
arr=np.array([[1,2,3],[4,5,6],[6,7,8]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [9]:
arr.ndim

2

In [10]:
np.random.randint(1,10,(4,4))

array([[8, 9, 1, 8],
       [2, 9, 5, 8],
       [5, 6, 5, 5],
       [9, 3, 3, 4]])

In [11]:
np.random.randint(1,10,(4,4,2))

array([[[3, 9],
        [4, 6],
        [3, 3],
        [8, 7]],

       [[7, 8],
        [1, 5],
        [6, 7],
        [1, 8]],

       [[8, 6],
        [9, 5],
        [4, 2],
        [6, 6]],

       [[6, 4],
        [4, 5],
        [9, 2],
        [5, 2]]])

In [12]:
np.random.randint(1,10,(2,3,3))

array([[[1, 1, 3],
        [9, 4, 6],
        [7, 8, 5]],

       [[1, 9, 1],
        [1, 6, 8],
        [9, 2, 2]]])

In [13]:
l=[1,2,3,4,5,6,5,4,3]

In [14]:
np.array(l)

array([1, 2, 3, 4, 5, 6, 5, 4, 3])

In [15]:
l1=[4,5,6,7,'sudh',3.45,True]

In [16]:
np.array(l1)
#it will convert all in string
# it will convert all element in higher element value 

array(['4', '5', '6', '7', 'sudh', '3.45', 'True'], dtype='<U32')

2