In [1]:
import numpy as np

In [2]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [3]:
type(np.array([2,3,4,5,6]))

numpy.ndarray

In [4]:
np.array([[2,3,4],[5,6,7]])

array([[2, 3, 4],
       [5, 6, 7]])

In [5]:
l=[[1,2,3,4],[5,6,7,8]]
l[0][0]

1

In [6]:
a=np.array([1,2,3,4],ndmin=3)

In [7]:
a

array([[[1, 2, 3, 4]]])

In [8]:
arr=np.array([[1,2,3],[4,5,6],[6,7,8]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [9]:
arr.ndim

2

In [10]:
np.random.randint(1,10,(4,4))

array([[6, 1, 4, 4],
       [3, 9, 2, 5],
       [8, 5, 6, 4],
       [6, 7, 4, 9]])

In [11]:
np.random.randint(1,10,(4,4,2))

array([[[1, 5],
        [2, 1],
        [7, 8],
        [2, 9]],

       [[9, 5],
        [5, 4],
        [8, 6],
        [3, 7]],

       [[6, 3],
        [2, 9],
        [1, 6],
        [1, 6]],

       [[9, 7],
        [3, 3],
        [6, 6],
        [4, 3]]])

In [12]:
np.random.randint(1,10,(2,3,3))

array([[[6, 6, 2],
        [7, 1, 8],
        [4, 5, 7]],

       [[9, 7, 4],
        [2, 3, 6],
        [7, 2, 1]]])

In [13]:
l=[1,2,3,4,5,6,5,4,3]

In [14]:
np.array(l)

array([1, 2, 3, 4, 5, 6, 5, 4, 3])

In [15]:
l1=[4,5,6,7,'sudh',3.45,True]

In [16]:
np.array(l1)
#it will convert all in string
# it will convert all element in higher element value 

array(['4', '5', '6', '7', 'sudh', '3.45', 'True'], dtype='<U32')

In [17]:
np.random.rand(3,10)

array([[0.25470437, 0.50868851, 0.48298488, 0.84208596, 0.87357607,
        0.13671214, 0.88162952, 0.62970282, 0.51384665, 0.19381023],
       [0.50880428, 0.76368881, 0.7812234 , 0.59287753, 0.31224408,
        0.40172958, 0.84092641, 0.82033875, 0.29513795, 0.11216059],
       [0.15310485, 0.10241067, 0.37153736, 0.23452099, 0.01610742,
        0.41635546, 0.81044259, 0.36897446, 0.52869737, 0.25828658]])

In [18]:
a4=np.random.randn(4,4)

In [19]:
l1=[[1,2,3,4,5,6,7,8,9]]

In [20]:
np.reshape(l1,(3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
a4.reshape(1,16)

array([[ 0.44923704, -1.34382456,  0.56064395, -1.67653099,  0.63367931,
         0.88100843, -0.08985549,  0.49124603,  0.73558405, -0.50011001,
         1.78728094,  1.41023956,  0.33574937,  0.18491333,  0.15409944,
         0.65077853]])

In [22]:
a4.reshape(2,4,2)

array([[[ 0.44923704, -1.34382456],
        [ 0.56064395, -1.67653099],
        [ 0.63367931,  0.88100843],
        [-0.08985549,  0.49124603]],

       [[ 0.73558405, -0.50011001],
        [ 1.78728094,  1.41023956],
        [ 0.33574937,  0.18491333],
        [ 0.15409944,  0.65077853]]])

In [23]:
l1

[[1, 2, 3, 4, 5, 6, 7, 8, 9]]

In [24]:
l1=np.array(l1)

In [25]:
l1

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [26]:
l1[0]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
l1[2:4]

array([], shape=(0, 9), dtype=int32)

In [28]:
l1[::2]

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [29]:
l1[::-1]

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [30]:
a3=[1,2,3,4,5,6,7,8,9]
a3=np.reshape(a3,(3,3))
a3=np.array(a3,ndmin=3)
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [31]:
a2=np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
a2[0]

array([1, 2, 3])

In [33]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [34]:
a2[1:,1:]

array([[5, 6]])

In [35]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [36]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [37]:
a2[[0,1],[1,2]]

array([2, 6])

In [38]:
a5=np.random.randint(2,90,(6,5))
a5

array([[49, 45, 62, 88, 72],
       [74, 73, 17, 46, 67],
       [26, 15, 87, 18, 59],
       [28, 74, 82, 89, 14],
       [10, 21, 29, 30, 12],
       [20, 62, 28, 11, 80]])

In [39]:
a5[a5>40]

array([49, 45, 62, 88, 72, 74, 73, 46, 67, 87, 59, 74, 82, 89, 62, 80])

In [40]:
a5

array([[49, 45, 62, 88, 72],
       [74, 73, 17, 46, 67],
       [26, 15, 87, 18, 59],
       [28, 74, 82, 89, 14],
       [10, 21, 29, 30, 12],
       [20, 62, 28, 11, 80]])

In [41]:
a5[0][1]=5

In [42]:
a5

array([[49,  5, 62, 88, 72],
       [74, 73, 17, 46, 67],
       [26, 15, 87, 18, 59],
       [28, 74, 82, 89, 14],
       [10, 21, 29, 30, 12],
       [20, 62, 28, 11, 80]])

In [43]:
a6=np.random.randint(0,3,(3,3))
a6

array([[1, 2, 1],
       [1, 0, 0],
       [1, 0, 0]])

In [44]:
a7=np.random.randint(0,3,(3,3))
a7

array([[0, 2, 0],
       [0, 0, 1],
       [0, 2, 2]])

In [45]:
# this is not a matrix multiplication
a6*a7

array([[0, 4, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [46]:
# this is a matrix multiplication
a6@a7

array([[0, 4, 4],
       [0, 2, 0],
       [0, 2, 0]])

In [47]:
a6/0

C:\Users\adity\AppData\Local\Temp\ipykernel_5212\1058679823.py:1: RuntimeWarning: divide by zero encountered in divide
  a6/0
C:\Users\adity\AppData\Local\Temp\ipykernel_5212\1058679823.py:1: RuntimeWarning: invalid value encountered in divide
  a6/0


array([[inf, inf, inf],
       [inf, nan, nan],
       [inf, nan, nan]])

In [48]:
a6

array([[1, 2, 1],
       [1, 0, 0],
       [1, 0, 0]])

In [49]:
a6**3

array([[1, 8, 1],
       [1, 0, 0],
       [1, 0, 0]], dtype=int32)

In [53]:
a8=np.zeros((4,4))
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [54]:
a9=np.ones((4,4))
a9

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
a9+10

array([[11., 11., 11., 11.],
       [11., 11., 11., 11.],
       [11., 11., 11., 11.],
       [11., 11., 11., 11.]])

In [57]:
a9+np.array([1,2,3,4])

array([[2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

In [60]:
np.array([1,2,3,4]).T

array([1, 2, 3, 4])

In [63]:
# we have to change 
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [64]:
a6

array([[1, 2, 1],
       [1, 0, 0],
       [1, 0, 0]])

In [65]:
a6.T

array([[1, 1, 1],
       [2, 0, 0],
       [1, 0, 0]])

In [66]:
a5

array([[49,  5, 62, 88, 72],
       [74, 73, 17, 46, 67],
       [26, 15, 87, 18, 59],
       [28, 74, 82, 89, 14],
       [10, 21, 29, 30, 12],
       [20, 62, 28, 11, 80]])

In [68]:
np.sqrt(a5)

array([[7.        , 2.23606798, 7.87400787, 9.38083152, 8.48528137],
       [8.60232527, 8.54400375, 4.12310563, 6.78232998, 8.18535277],
       [5.09901951, 3.87298335, 9.32737905, 4.24264069, 7.68114575],
       [5.29150262, 8.60232527, 9.05538514, 9.43398113, 3.74165739],
       [3.16227766, 4.58257569, 5.38516481, 5.47722558, 3.46410162],
       [4.47213595, 7.87400787, 5.29150262, 3.31662479, 8.94427191]])

In [69]:
np.exp(a5)

array([[1.90734657e+21, 1.48413159e+02, 8.43835667e+26, 1.65163625e+38,
        1.85867175e+31],
       [1.37338298e+32, 5.05239363e+31, 2.41549528e+07, 9.49611942e+19,
        1.25236317e+29],
       [1.95729609e+11, 3.26901737e+06, 6.07603023e+37, 6.56599691e+07,
        4.20121040e+25],
       [1.44625706e+12, 1.37338298e+32, 4.09399696e+35, 4.48961282e+38,
        1.20260428e+06],
       [2.20264658e+04, 1.31881573e+09, 3.93133430e+12, 1.06864746e+13,
        1.62754791e+05],
       [4.85165195e+08, 8.43835667e+26, 1.44625706e+12, 5.98741417e+04,
        5.54062238e+34]])

In [70]:
np.log10(a5)

array([[1.69019608, 0.69897   , 1.79239169, 1.94448267, 1.8573325 ],
       [1.86923172, 1.86332286, 1.23044892, 1.66275783, 1.8260748 ],
       [1.41497335, 1.17609126, 1.93951925, 1.25527251, 1.77085201],
       [1.44715803, 1.86923172, 1.91381385, 1.94939001, 1.14612804],
       [1.        , 1.32221929, 1.462398  , 1.47712125, 1.07918125],
       [1.30103   , 1.79239169, 1.44715803, 1.04139269, 1.90308999]])

In [71]:
range(1,10)

range(1, 10)

In [72]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [74]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [76]:
list(range(0,10,2.5))
# it can be only integer

TypeError: 'float' object cannot be interpreted as an integer

In [77]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
np.array(list(range(0,10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
np.arange(0,10,1.5)

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [80]:
np.linspace(2,3,50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [82]:
np.logspace(2,4,num=4,base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [84]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [85]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])